name: health report

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 0 * * *'
  workflow_dispatch:

jobs:
  report:
    runs-on: windows-latest
    steps:
    - name: Health Report
      uses: Editst/SYSU-HealthReport@master
      with:
        netid: ${{secrets.NETID}}
        password: ${{secrets.PASSWORD}}
        ocr_token: ${{secrets.OCR_TOKEN}}
        tg_bot_token: ${{secrets.TG_BOT_TOKEN}}
        tg_chatid: ${{secrets.TG_CHATID}}